using Accord.MachineLearning.VectorMachines;
using Accord.Statistics.Kernels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;

namespace TrafficSignRecognizer.API.Models.ClassificationModel
{
    public sealed class SURFModel
    {
        // Here we will store our support vector machine that will be
        // used to classify the feature vectors generated by the BoW.
        MulticlassSupportVectorMachine<IKernel> ksvm;

        public SURFModel(Bitmap[] imgs)
        {

        }
    }
}
